plugins {
    id 'com.android.application'
}

android {
    namespace 'it.arcanea.italia'
    compileSdk 34
    buildToolsVersion "36.0.0"

    signingConfigs {
        release {
            def propsFile = rootProject.file("keystore.properties")
            def props = new Properties()
            props.load(new FileInputStream(propsFile))
            storeFile file(props["storeFile"])
            storePassword props["storePassword"]
            keyAlias props["keyAlias"]
            keyPassword props["keyPassword"]
        }
    }

    defaultConfig {
        applicationId 'it.arcanea.italia'
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
}

